apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper
  namespace: job-application
spec:
  # Run every 20 minutes for testing
  schedule: "*/20 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      # Job timeout: 10 minutes
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
            - name: scraper
              image: job-scraper:latest
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              envFrom:
                - configMapRef:
                    name: scraper-config
              env:
                - name: APIFY_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: job-application-secrets
                      key: APIFY_API_TOKEN
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: job-application-secrets
                      key: DATABASE_URL
          restartPolicy: OnFailure
