apiVersion: batch/v1
kind: CronJob
metadata:
  name: applicant
  namespace: job-application
spec:
  # Run daily (placeholder - not yet implemented)
  schedule: "0 9 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: true  # Suspended until implemented
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: applicant
              image: applicant-image
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "100m"
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              envFrom:
                - configMapRef:
                    name: applicant-config
          restartPolicy: OnFailure
