"""
Email Service using Resend.
Sends job application packages (CV + cover letter) to the user.
"""

import base64
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

import resend
from loguru import logger

from shared.config import Settings, get_settings


@dataclass
class EmailResult:
    """Result of email sending."""
    success: bool
    email_id: Optional[str] = None
    error: Optional[str] = None


class EmailService:
    """Sends job application packages via Resend."""

    def __init__(self, settings: Optional[Settings] = None):
        self.settings = settings or get_settings()
        resend.api_key = self.settings.resend_api_key.get_secret_value()

    def _format_email_body(
        self,
        job: dict[str, Any],
        cover_letter: str,
        ats_keywords: list[str],
    ) -> str:
        """Format the email body with job details and cover letter."""
        title = job.get("title", "Unknown Position")
        company = job.get("company", "Unknown Company")
        location = job.get("location", "Unknown Location")
        apply_url = job.get("apply_url", job.get("url", ""))
        llm_match_score = job.get("llm_match_score", "N/A")
        llm_match_reasoning = job.get("llm_match_reasoning", "")

        # Format ATS keywords
        keywords_str = ", ".join(ats_keywords[:10]) if ats_keywords else "N/A"

        body = f"""Hi Ernest,

A new job match is ready for your application!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 Position: {title}
🏢 Company: {company}
📍 Location: {location}
⭐ Match Score: {llm_match_score}/5

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

WHY THIS IS A GOOD MATCH:
{llm_match_reasoning}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ATS KEYWORDS IDENTIFIED:
{keywords_str}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔗 APPLY HERE: {apply_url}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COVER LETTER (ready to paste):

{cover_letter}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Your tailored CV is attached as PDF.

Good luck with your application!

---
This email was automatically generated by Job Application Tool.
"""
        return body

    def _format_html_body(
        self,
        job: dict[str, Any],
        cover_letter: str,
        ats_keywords: list[str],
    ) -> str:
        """Format HTML email body for better readability."""
        title = job.get("title", "Unknown Position")
        company = job.get("company", "Unknown Company")
        location = job.get("location", "Unknown Location")
        apply_url = job.get("apply_url", job.get("url", ""))
        llm_match_score = job.get("llm_match_score", "N/A")
        llm_match_reasoning = job.get("llm_match_reasoning", "")

        # Format keywords as badges
        keywords_html = " ".join(
            f'<span style="background:#e0e7ff;padding:2px 8px;border-radius:4px;margin:2px;display:inline-block;font-size:12px;">{kw}</span>'
            for kw in ats_keywords[:10]
        ) if ats_keywords else "N/A"

        # Convert cover letter newlines to HTML
        cover_letter_html = cover_letter.replace("\n", "<br>")

        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }}
        .header h1 {{ margin: 0; font-size: 18px; }}
        .header .company {{ font-size: 24px; font-weight: bold; margin-top: 5px; }}
        .section {{ background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 15px; }}
        .section h2 {{ margin-top: 0; color: #667eea; font-size: 14px; text-transform: uppercase; letter-spacing: 1px; }}
        .score {{ font-size: 32px; font-weight: bold; color: #667eea; }}
        .apply-btn {{ display: inline-block; background: #667eea; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: bold; margin: 10px 0; }}
        .apply-btn:hover {{ background: #5a67d8; }}
        .cover-letter {{ background: white; border-left: 3px solid #667eea; padding: 15px; margin: 15px 0; }}
        .footer {{ color: #666; font-size: 12px; margin-top: 20px; padding-top: 15px; border-top: 1px solid #eee; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📋 {title}</h1>
        <div class="company">🏢 {company}</div>
        <div>📍 {location}</div>
    </div>

    <div class="section">
        <h2>⭐ Match Score</h2>
        <div class="score">{llm_match_score}/5</div>
    </div>

    <div class="section">
        <h2>Why This Is A Good Match</h2>
        <p>{llm_match_reasoning}</p>
    </div>

    <div class="section">
        <h2>ATS Keywords Identified</h2>
        <div>{keywords_html}</div>
    </div>

    <div style="text-align: center; margin: 20px 0;">
        <a href="{apply_url}" class="apply-btn">🔗 Apply Now</a>
    </div>

    <div class="section">
        <h2>Cover Letter (Ready to Paste)</h2>
        <div class="cover-letter">
            {cover_letter_html}
        </div>
    </div>

    <p>📎 Your tailored CV is attached as PDF.</p>

    <div class="footer">
        This email was automatically generated by Job Application Tool.
    </div>
</body>
</html>"""
        return html

    def _read_attachment(self, file_path: Path) -> Optional[dict]:
        """Read file and prepare as email attachment."""
        try:
            with open(file_path, "rb") as f:
                content = base64.standard_b64encode(f.read()).decode("utf-8")

            return {
                "filename": file_path.name,
                "content": content,
            }
        except Exception as e:
            logger.error(f"Failed to read attachment {file_path}: {e}")
            return None

    def send_application_package(
        self,
        job: dict[str, Any],
        cv_pdf_path: Path,
        cover_letter: str,
        ats_keywords: list[str],
        cover_letter_pdf_path: Optional[Path] = None,
    ) -> EmailResult:
        """
        Send job application package via email.

        Args:
            job: Job data dict
            cv_pdf_path: Path to tailored CV PDF
            cover_letter: Cover letter text
            ats_keywords: Extracted ATS keywords
            cover_letter_pdf_path: Optional path to cover letter PDF

        Returns:
            EmailResult with success status
        """
        title = job.get("title", "Unknown Position")
        company = job.get("company", "Unknown Company")

        # Prepare attachments
        attachments = []

        cv_attachment = self._read_attachment(cv_pdf_path)
        if cv_attachment:
            attachments.append(cv_attachment)
        else:
            return EmailResult(
                success=False,
                error="Failed to read CV PDF attachment",
            )

        if cover_letter_pdf_path and cover_letter_pdf_path.exists():
            cl_attachment = self._read_attachment(cover_letter_pdf_path)
            if cl_attachment:
                attachments.append(cl_attachment)

        # Prepare email
        subject = f"[Job Application Ready] {title} at {company}"
        text_body = self._format_email_body(job, cover_letter, ats_keywords)
        html_body = self._format_html_body(job, cover_letter, ats_keywords)

        try:
            params = {
                "from": self.settings.resend_from_email,
                "to": [self.settings.resend_to_email],
                "subject": subject,
                "text": text_body,
                "html": html_body,
                "attachments": attachments,
            }

            response = resend.Emails.send(params)

            if response and hasattr(response, "id"):
                logger.info(f"Email sent successfully for {title} at {company}, ID: {response.id}")
                return EmailResult(success=True, email_id=response.id)
            elif isinstance(response, dict) and "id" in response:
                logger.info(f"Email sent successfully for {title} at {company}, ID: {response['id']}")
                return EmailResult(success=True, email_id=response["id"])
            else:
                logger.warning(f"Email sent but no ID returned: {response}")
                return EmailResult(success=True)

        except Exception as e:
            logger.error(f"Failed to send email for {title} at {company}: {e}")
            return EmailResult(success=False, error=str(e))
